services:
  embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:1.8
    restart: always
    environment:
      MODEL_ID: Qwen/Qwen3-Embedding-0.6B
    volumes:
      - ./volumes/embedding/models:/data
    ports:
      - "${EXPOSE_TEI_PORT:-8090}:80"
    command: ["--auto-truncate"]
    deploy:
      resources:
        limits:
          memory: 4G
